# Generated by Django 3.1.5 on 2021-01-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210122_1016'),
        ('registration', '0002_auto_20210121_1335'),
        ('registration', '0002_auto_20210120_0957'),
    ]

    operations = [
    ]
