# Generated by Django 3.1.5 on 2021-01-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commentary', models.CharField(max_length=300)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.gender')),
                ('type_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.type_animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animal',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Housing_planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.type_animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user_data')),
            ],
            options={
                'verbose_name': 'Housing planning',
                'verbose_name_plural': 'Planning des hébergements',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Housing_animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.animal')),
                ('housing_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.housing_planning')),
            ],
            options={
                'verbose_name': 'Housing animal',
                'verbose_name_plural': 'Housing animal',
                'ordering': ['animal'],
            },
        ),
    ]
